apiVersion: v1
kind: Service
metadata:
  name: {{ include "nmap.fullname" . }}
  labels:
    {{- include "nmap.labels" . | nindent 4 }}
spec:
# we need Local policy and healthCheckNodePort set to get rid of logs pollution
  {{- if (.Values.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
  {{- end }}
  {{- if .Values.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.externalTrafficPolicy }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "nmap.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nmap.fullname" . }}-internal
  labels:
    {{- include "nmap.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.serviceInternal.port }}
      targetPort: {{ .Values.serviceInternal.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.adminListener.port }}
      targetPort: {{ .Values.adminListener.port }}
      protocol: TCP
      name: adminlistener
  selector:
    # app.kubernetes.io/name: {{ include "nmap.name" . }}
    {{- include "nmap.selectorLabels" . | nindent 4 }}

  