########################################
###    CENM configuration options    ###
########################################

# Display more messages while executing Kubernetes deployment
bashDebug: false

# Docker images to use by the Identity Manager Service Helm chart
dockerImage:
  name: corda/enterprise-identitymanager
  tag: 1.6-zulu-openjdk8u392
  pullPolicy: Always

# Docker images to use by CENM CLI Helm chart
dockerImageCli:
  name: corda/enterprise-cli
  tag: 1.6-zulu-openjdk8u392
  pullPolicy: Always

# Volume size for etc/ directory
volumeSizeIdmanEtc: 1Gi

# Volume size for logs/ directory
volumeSizeIdmanLogs: 10Gi

# Volume size for h2/ directory
volumeSizeIdmanH2: 10Gi

# Configuration for database
database:
  driverClassName: "org.h2.Driver"
  jdbcDriver: ""
  url: "jdbc:h2:file:./h2/identity-manager-persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=0;AUTO_SERVER_PORT=0"
  user: "example-db-user"
  password: "example-db-password"
  runMigration: true

# Required parameter
acceptLicense:

# Memory size allocated to the main Identity Manager Service container (in GB)
cordaJarMx: 1

idmanJar:
  # value for java -Xmx parameter
  xmx: 1G
  # The directory where the Identity Manager Service jar file is stored
  path: bin
  # The directory where the Signing Service configuration is stored
  configPath: etc

# Sleep time (in seconds) after an error occured
sleepTimeAfterError: 120

# Auth Service port
authPort: 8081

# Revocation port
serviceRevocation:
  port: 5053

# Enable container displaying live logs
logsContainersEnabled: true

########################################
###   Kubernetes related settings    ###
########################################

# Name of Kubernetes secret storing credentials to Docker registry
imagePullSecrets:
  - name: cenm-registry

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

### This has been commented out due to a double `service:` block causing incorrect yaml
### This service key looks like the anomaly wrt the other helm charts so it has been removed
# service:
#   type: ClusterIP
#   port: 80

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 1Gi
  requests:
    # cpu: 100m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

## Liveness and readiness probe values
## Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
##
livenessProbe:
  enabled: false
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  enabled: false
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

storageClass: cenm

# Local policy and healthCheckNodePort are set to get rid of logs pollution
healthCheckNodePort: 0
externalTrafficPolicy: Local

service:
  type: LoadBalancer
  port: 10000

serviceInternal:
  type: LoadBalancer
  port: 5052

adminListener:
  type: ClusterIP
  port: 6000
