---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-zone-h2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeZoneH2 }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-zone-logs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeZoneLogs }}
