########################################
###    CENM configuration options    ###
########################################

# Display more messages while executing Kubernetes deployment
bashDebug: false

image:
  repository: corda/enterprise-zone
  tag: 1.5.3-zulu-openjdk8u242
  pullPolicy: Always

# Database configuration
database:
  driverClassName: "org.h2.Driver"
  jdbcDriver: ""
  url: "jdbc:h2:file:./h2/zone-persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=0;AUTO_SERVER_PORT=0"
  user: "example-db-user"
  password: "example-db-password"
  runMigration: true

# Required parameter
acceptLicense:

# Volume size for h2/ directory
volumeSizeZoneH2: 1Gi

# Volume size for logs/ directory
volumeSizeZoneLogs: 5Gi

zoneJar:
  # value for java -Xmx
  xmx: 1G
  # The directory where the Signing Service .jar file is stored
  path: bin
  # The directory where the Signing Service configuration is stored
  configPath: etc

# Definition of the Auth Service
authService:
  host: auth
  port: 8081

# Sleep time (in seconds) after an error occured
sleepTimeAfterError: 120

# Enable container displaying live logs
logsContainersEnabled: true

########################################
###   Kubernetes related settings    ###
########################################

# Name of Kubernetes secret storing credentials to Docker registry
imagePullSecrets:
  - name: cenm-registry

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
  #   cpu: 100m
    memory: 1Gi
  requests:
  #   cpu: 100m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

listenerPort:
  enm: "25000"
  admin: "12345"

storageClass: cenm
